name: Create Merged File And Schema

on:
  push:
    paths:
      - versions/**

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pydantic pytest

      - name: Test version version data files
        run: |
          pytest ./utils/test_versions.py

      - name: Creating a merged version file
        run: |
          python3 ./utils/create_merged.py

      - name: Creating a schema for version data
        run: |
          python3 ./utils/create_schema.py

      - name: Commit changes
        run:  |
          git config user.name github-actions
          git config user.email github-actions.github.com
          git add .
          git commit -m "Generated merged version file and version schema."

      - name: Push changes
        run:  |
          git push
